exclude_paths:
  - "editor.md/**"
  - "PWA/**"
  - "TEST/**"
  - "Github_emojis/**"
  - "twemoji/**"
  - "**/*.png"
  - "**/*.ico"
  - "**/*.gif"
  - "**/*.woff"
  - "**/*.woff2"
  - "**/*.ttf"
  - "**/*.eot"
  - "**/*.otf"
