export const paramDefs = {
  min_distance: {
    key: 'min_distance',
    label: '最小距离 (米)',
    type: 'number',
    default: 1000,
    min: 100,
    max: 50000,
    step: 100,
    group: 'basic',
    description: '任务最小跑步距离',
  },
  max_distance: {
    key: 'max_distance',
    label: '最大距离 (米)',
    type: 'number',
    default: 3000,
    min: 100,
    max: 50000,
    step: 100,
    group: 'basic',
    description: '任务最大跑步距离',
  },
  min_speed: {
    key: 'min_speed',
    label: '最小速度 (km/h)',
    type: 'number',
    default: 3,
    min: 1,
    max: 20,
    step: 0.5,
    group: 'basic',
    description: '最小跑步速度',
  },
  max_speed: {
    key: 'max_speed',
    label: '最大速度 (km/h)',
    type: 'number',
    default: 10,
    min: 1,
    max: 20,
    step: 0.5,
    group: 'basic',
    description: '最大跑步速度',
  },
  step_length: {
    key: 'step_length',
    label: '步长 (米)',
    type: 'number',
    default: 0.75,
    min: 0.3,
    max: 2.0,
    step: 0.05,
    group: 'displacement',
    description: '每步距离',
  },
  gps_accuracy: {
    key: 'gps_accuracy',
    label: 'GPS精度',
    type: 'number',
    default: 5,
    min: 1,
    max: 50,
    step: 1,
    group: 'advanced',
    description: 'GPS定位精度 (米)',
  },
  point_interval: {
    key: 'point_interval',
    label: '打点间隔 (秒)',
    type: 'number',
    default: 3,
    min: 1,
    max: 30,
    step: 1,
    group: 'time',
    description: '位置上报间隔',
  },
  rest_probability: {
    key: 'rest_probability',
    label: '休息概率 (%)',
    type: 'number',
    default: 5,
    min: 0,
    max: 100,
    step: 1,
    group: 'advanced',
    description: '随机休息概率',
  },
  rest_duration_min: {
    key: 'rest_duration_min',
    label: '最小休息 (秒)',
    type: 'number',
    default: 3,
    min: 1,
    max: 60,
    step: 1,
    group: 'time',
    description: '最短休息时间',
  },
  rest_duration_max: {
    key: 'rest_duration_max',
    label: '最大休息 (秒)',
    type: 'number',
    default: 10,
    min: 1,
    max: 120,
    step: 1,
    group: 'time',
    description: '最长休息时间',
  },
  ignore_task_time: {
    key: 'ignore_task_time',
    label: '忽略任务时间限制',
    type: 'checkbox',
    default: false,
    group: 'other',
    description: '是否忽略任务时间窗口限制',
  },
  auto_attendance_enabled: {
    key: 'auto_attendance_enabled',
    label: '自动签到',
    type: 'checkbox',
    default: false,
    group: 'other',
    description: '是否启用自动签到打卡',
  },
  auto_attendance_refresh_s: {
    key: 'auto_attendance_refresh_s',
    label: '签到刷新间隔 (秒)',
    type: 'number',
    default: 300,
    min: 60,
    max: 3600,
    step: 30,
    group: 'other',
    description: '自动签到刷新间隔',
  },
}

export const paramGroups = [
  { key: 'basic', label: '基本参数' },
  { key: 'time', label: '时间参数' },
  { key: 'displacement', label: '位移参数' },
  { key: 'advanced', label: '高级参数' },
  { key: 'other', label: '其他参数' },
]

export function getParamsByGroup(group) {
  return Object.values(paramDefs).filter(p => p.group === group)
}
