# 此工作流使用了 GitHub 未认证的 Actions。
# 它们由第三方提供，并受单独的服务条款、隐私政策和支持文档约束。

# 此工作流会检出代码，执行 Codacy 安全扫描，
# 并将结果集成到 GitHub 高级安全代码扫描功能中。
# 有关 Codacy 安全扫描 Action 的使用和参数，请参阅：
# https://github.com/codacy/codacy-analysis-cli-action
# 有关 Codacy Analysis CLI 的更多信息，请参阅：
# https://github.com/codacy/codacy-analysis-cli

name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # 以下分支必须是上面分支的子集
    branches: [ "main" ]
  schedule:
    - cron: '37 18 * * 3'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # 供 actions/checkout 获取代码
      security-events: write # 供 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 私有仓库时，供 github/codeql-action/upload-sarif 获取 Action 运行状态
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      # 将仓库检出到 GitHub Actions 运行器
      - name: Checkout code
        uses: actions/checkout@v4

      # 执行 Codacy Analysis CLI 并生成 SARIF 输出，包含分析过程中识别的安全问题
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          # 请查看 https://github.com/codacy/codacy-analysis-cli#project-token 获取 Codacy 仓库的项目令牌
          # 也可以省略令牌，仅运行支持默认配置的工具
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          # 调整非安全问题的严重性
          gh-code-scanning-compat: true
          # 强制退出码为 0，以便生成 SARIF 文件
          # 这会将 PR 拒绝的控制权交给 GitHub 端
          max-allowed-issues: 2147483647

      # 上传上一步生成的 SARIF 文件
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
