# 此工作流会检出代码、执行 Codacy 安全扫描，
# 并将结果集成到
# GitHub Advanced Security 代码扫描功能中。有关
# Codacy 安全扫描 Action 的用法和参数，请参见：
# https://github.com/codacy/codacy-analysis-cli-action
# 有关 Codacy Analysis CLI 的更多信息，请参见：
# https://github.com/codacy/codacy-analysis-cli

name: Codacy 安全扫描

on:
  push:
    branches: [ "main" ]
  pull_request:
    # 下方分支必须是上方分支的子集
    branches: [ "main" ]
  schedule:
    - cron: '17 9 * * 4'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # 供 actions/checkout 拉取代码
      security-events: write # 供 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read # 私有仓库场景下，供 github/codeql-action/upload-sarif 获取 Action 运行状态
    name: Codacy 安全扫描
    runs-on: ubuntu-latest
    steps:
      # 将仓库代码检出到 GitHub Actions 运行器
      - name: 检出代码
        uses: actions/checkout@v4

      # 执行 Codacy Analysis CLI，并输出包含扫描结果的 SARIF 文件
      - name: 运行 Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          # 参考 https://github.com/codacy/codacy-analysis-cli#project-token 获取项目令牌
          # 也可省略令牌，仅运行支持默认配置的工具
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          # 调整非安全问题的严重级别映射
          gh-code-scanning-compat: true
          # 强制返回 0 退出码，以确保 SARIF 文件可生成
          # 由 GitHub 侧决定是否据此阻止 PR 合并
          max-allowed-issues: 2147483647

      # 上传上一步生成的 SARIF 结果文件
      - name: 上传 SARIF 结果文件
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
