# EthicalCheck解决了在开发和生产中持续进行API安全测试的关键需求。

# EthicalCheck provides the industry’s only free & automated API security testing service that uncovers security vulnerabilities using OWASP API list.
# 开发人员依赖EthicalCheck来评估每个更新和发布，确保没有API使用可利用的漏洞进入生产环境。

# 你开发应用程序和API，我们为你提供完整和持续的安全测试，加速开发。

# 使用EthicalCheck了解你的API和应用程序是否安全 – 我们的免费和自动化API安全测试服务。

# EthicalCheck如何工作？
# EthicalCheck按照以下简单步骤运作。
# 1. 安全测试。
# 提供你的OpenAPI规范或开始使用公共Postman集合URL。
# EthicalCheck立即检查你的API并为安全测试创建API端点映射。
# 然后自动创建数百个安全测试，以非侵入式的方式全面测试身份验证、授权和OWASP漏洞。这些测试涉及OWASP API安全类别，包括OAuth 2.0、JWT、速率限制等。

# 2. 报告。
# EthicalCheck生成安全测试报告，包括所有测试的端点、覆盖图、异常和漏洞。
# 漏洞已完全分类，包含CVSS分数、严重程度、端点信息和OWASP标记。


# 这是一个启动工作流，帮助你开始使用EthicalCheck操作

name: EthicalCheck-Workflow

# 控制工作流何时运行
on:
  # 仅在"main"分支上的push或pull request事件期间触发工作流
  # 根据你的DevSecOps流程自定义触发事件
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 12 * * 2'

  # 允许你从Actions选项卡手动运行此工作流
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write # 用于github/codeql-action/upload-sarif上传SARIF结果
      actions: read # 仅对私有存储库需要，用于github/codeql-action/upload-sarif获取Action运行状态
    runs-on: ubuntu-latest

    steps:
       - name: EthicalCheck  免费和自动化API安全测试服务
         uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
         with:
          # OpenAPI规范URL或Swagger路径或公共Postman集合URL。
          oas-url: "http://netbanking.apisec.ai:8080/v2/api-docs"
          # 渗透测试报告将发送到的电子邮件地址。
          email: "xxx@apisec.ai"
          sarif-result-file: "ethicalcheck-results.sarif"

       - name: 上传sarif文件到仓库
         uses: github/codeql-action/upload-sarif@v3
         with:
          sarif_file: ./ethicalcheck-results.sarif

